### ISSUE TITLE
Setup.py fails to install

### ISSUE THREAD

**Issue by fake-name** [fake-name/pySignalHound#3]
Received via e-mail

> hi,wolf:
>  
> I want to use  pySignalHound-master.zip downoad from github.com,but i can't find the  primary file "SignalHound.py".
> So i don't run cross  "from app.SignalHound import SignalHound" in file  tests.py. What can i do?
>  
> thank you a lot.  look forward your replay.
>  
> BestRegard!
>  
> Andi
>  
> 2016-12-11
> hxtj_wangjb

![clip 12-11-23-30-43](https://cloud.githubusercontent.com/assets/1401239/21085683/94f9e52e-bfc9-11e6-9026-6d65de4c011d.png)

**Comment by fake-name** [comment]
It looks like you're running an old version of the tests file, I'm not sure from where.

[The current version of the library uses](https://github.com/fake-name/pySignalHound/blob/master/tests.py#L25) `from SignalHound import SignalHound` to import the library.

Try installing from git: `pip install git+https://github.com/fake-name/pySignalHound.git`. I suspect the version of the library in PyPi is simply out of date.

In any event, the "primary file" is actually [`SignalHound/__init__.py`](https://github.com/fake-name/pySignalHound/blob/master/SignalHound/__init__.py), though once the package is installed, you should simply be able to do `from SignalHound import SignalHound; instance=SignalHound()`.

**Comment by fake-name** [comment]
That change should quash those particular warnings.

**Comment by andi2009** [comment]
Thank you fake-name.
I have buy a BB60C module.
I fix the MANIFEST.in file as your up guide.and connect BB60C to my PC,Then i use command:
    >> python tests.py ststus,  
the message disp BB60C MODULE open error!But when i use spike application,the device is OK.
 the log message as follow:

    :\python_bbapi\pySignalHound-master1\pySignalHound-master>python tests.py status
    etting up loggers.... done
    016-12-13 09:36:16,029 - Main.DeviceInt - INFO - Opening DLL
    016-12-13 09:36:16,039 - Main.DeviceInt - INFO - Found dll located at C:\Python27\DLLs\bb_api.dll
    016-12-13 09:36:16,042 - Main.DeviceInt - INFO - Opening Device
    raceback (most recent call last):
     File "tests.py", line 560, in <module>
       go()
     File "tests.py", line 540, in go
       sh = SignalHound()
     File "D:\python_bbapi\pySignalHound-master1\pySignalHound-master\SignalHound\__init__.py", line 139, in __init__
       self.openDevice()
     File "D:\python_bbapi\pySignalHound-master1\pySignalHound-master\SignalHound\__init__.py", line 188, in openDevice
       raise ValueError("Could not open device!")
    alueError: Could not open device!
    016-12-13 09:36:16,121 - Main.DeviceInt - INFO - Deleting SignalHound Interface Class
    016-12-13 09:36:16,124 - Main.DeviceInt - INFO - Force Closing.
    016-12-13 09:36:16,125 - Main.DeviceInt - INFO - Forcing DLL handle closed
    016-12-13 09:36:16,128 - [31mMain.DeviceInt[0m - [22mINFO - Deleting SignalHound Interface Class[0m
    016-12-13 09:36:16,128 - [31mMain.DeviceInt[0m - [22mINFO - Force Closing.[0m
    016-12-13 09:36:16,131 - [31mMain.DeviceInt[0m - [22mINFO - Closing Device with handle num: 0[0m
    016-12-13 09:36:16,132 - [31mMain.DeviceInt[0m - [22mINFO - Running acquistion aborted.[0m
    016-12-13 09:36:16,138 - [31mMain.DeviceInt[0m - [22mINFO - Closed Device with handle num: 0[0m
    016-12-13 09:36:16,140 - [31mMain.DeviceInt[0m - [22mINFO - Forcing DLL handle closed[0m

    :\python_bbapi\pySignalHound-master1\pySignalHound-master>

**Comment by fake-name** [comment]
Hmmm, the DLL is failing to open the device. In this case, `bbOpenDevice()` is returning the `bbDeviceNotOpenErr` flag. 

I'm not sure what's causing this issue, as it's down in the SignalHoud DLL. It's possible (probable, even), that the SignalHound firmware has changed enough that it no longer works with the old version of the DLL packed with installer. 

It may be possible to replace the packaged version of the DLL (located at `C:\Python27\DLLs\bb_api.dll` on your system) with a current version from https://signalhound.com/support/product-downloads/bb60c-bb60a-downloads/ I'm not sure this would fix the problem, but it's where I'd look.

Aside from that, I don't really know what's going on. I'm unfortunately no longer at the job where I had a SignalHound, so I'm unable to perform any further testing at the moment.

**Comment by andi2009** [comment]
thank you wolf.
I am download spike software and install it,the spike application is run normal.
Then i copy spike's bb_api.dll and  ftd2xx.dll file to overwrite  C:\Python27\DLLs\bb_api.dll, then run >> python tests.py ststus,;
The log message just like up comment;So I think the module and bb_api.dll file is same version and normal.
Any advice about this?
Thank you!

**Comment by fake-name** [comment]
Can you compile their demo projects?

I'm really not sure what else to tell you. Checking the documentation, you're seeing `bbOpenDevice` return `bbDeviceNotOpenErr`, so the call is failing in the DLL outside of anything python related.

The documentation says the following about this error:

> The device was unable to open. This can be returned for many reasons
> such as the device is not physically connected, eight devices are already
> open or there is an issue with the USB 3.0 connection

You do need to be careful that you use the right DLL version for your python (e.g. 32 bit dll for 32 bit python, 64 bit dll for 64 bit python), but I'm pretty sure the DLL open should have earlier on if you have a bit size mismatch.

One possibility is that SignalHound have changed their calling convention for the DLL. No idea why they'd do that, but it could be possible.

It might be worth experimenting with the DLL calling convention. Basically, right now, the library assumes [C calling convention](https://docs.python.org/3/library/ctypes.html#ctypes.CDLL). Try changing [the line here](https://github.com/fake-name/pySignalHound/blob/master/SignalHound/__init__.py#L120) from `self.dll = ct.CDLL(libPath)` to `self.dll = ct.WinDLL(libPath)`.

If that doesn't fix it, and their examples run fine, I have no idea what's going on.

**Comment by andi2009** [comment]
Thank you wolf.
I am creat a programe to test open device function,code just  like:

	int handle;
	int myerr = 0;
	// Attempt to open a connected device
	if(bbOpenDevice(&handle) != bbNoError) {
	//myErrorRoutine("Device didn't open
		myerr = 1;
  	}
I found the return Value is bbNoError;

My python version is python2.7.6  / 64-bit, I test both 32/b4 bit bb_api.dll to this script.  when use 32-bit, the log out is warning the dll is not a win32 dll. But 64-bit has no warning message;

I changed the  from self.dll = ct.CDLL(libPath) to self.dll = ct.WinDLL(libPath).  also unnormal;
I will try another way to test.
Thank your help.

Andi

**Comment by andi2009** [comment]
hi,wolf:
I appended c:\python27\dlls path to windows path,and then the device is open success.
thank you;

andi

**Comment by andi2009** [comment]
hi,wolf:
When i run>> python tests callback, the function 'bbConfigureTrigger' not found. 
Please give me some advice.
thank you;

the out log as follow:

Connected to pydev debugger (build 163.8233.8)
Setting up loggers.... done
2016-12-13 17:08:12,500 - Main.DeviceInt - INFO - Opening DLL
2016-12-13 17:08:12,503 - Main.DeviceInt - INFO - Found dll located at C:\Python27\DLLs\bb_api.dll
2016-12-13 17:08:12,505 - Main.DeviceInt - INFO - Opening Device
2016-12-13 17:08:14,803 - Main.DeviceInt - INFO - Querying device for model information
2016-12-13 17:08:14,805 - Main.DeviceInt - INFO - Call to getDeviceType succeeded. Type = BB60C
2016-12-13 17:08:14,805 - Main.DeviceInt - INFO - Opened Device with handle num: 0
2016-12-13 17:08:14,806 - Main.DeviceInt - INFO - Setting device frequency center & span settings.
2016-12-13 17:08:14,808 - Main.DeviceInt - INFO - Call to configureCenterSpan succeeded.
2016-12-13 17:08:14,809 - Main.DeviceInt - INFO - Setting device reference level and attentuation.
2016-12-13 17:08:14,809 - Main.DeviceInt - INFO - Call to configureLevel succeeded.
2016-12-13 17:08:14,812 - Main.DeviceInt - INFO - Setting device reference gain.
2016-12-13 17:08:14,812 - Main.DeviceInt - INFO - Call to configureGain succeeded.
2016-12-13 17:08:14,813 - Main.DeviceInt - INFO - Setting device sweep coupling settings.
2016-12-13 17:08:14,815 - Main.DeviceInt - INFO - configureSweepCoupling Succeeded.
2016-12-13 17:08:14,816 - Main.DeviceInt - INFO - Setting device FFT windowing function.
2016-12-13 17:08:14,818 - Main.DeviceInt - INFO - Call to configureWindow succeeded.
2016-12-13 17:08:14,819 - Main.DeviceInt - INFO - Setting device video processing units.
2016-12-13 17:08:14,819 - Main.DeviceInt - INFO - Call to configureProcUnits succeeded.
2016-12-13 17:08:14,819 - Main.DeviceInt - INFO - Setting device trigger configuration.
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/python_bbapi/pySignalHound-master1/pySignalHound-master/tests.py", line 560, in <module>
    go()
  File "D:/python_bbapi/pySignalHound-master1/pySignalHound-master/tests.py", line 546, in go
    funcs[sys.argv[1]](sh)
  File "D:/python_bbapi/pySignalHound-master1/pySignalHound-master/tests.py", line 67, in testCallback
    sh.configureTrigger("none", "rising-edge", 0, 5)
  File "D:/python_bbapi/pySignalHound-master1/pySignalHound-master\SignalHound\__init__.py", line 969, in configureTrigger
    err = self.dll.bbConfigureTrigger(self.deviceHandle, trigType, edge, level, timeout)
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'bbConfigureTrigger' not found
2016-12-13 17:08:14,854 - Main.DeviceInt - INFO - Deleting SignalHound Interface Class
2016-12-13 17:08:14,855 - Main.DeviceInt - INFO - Force Closing.
2016-12-13 17:08:14,855 - Main.DeviceInt - INFO - Closing Device with handle num: 0
2016-12-13 17:08:14,855 - Main.DeviceInt - INFO - Running acquistion aborted.
2016-12-13 17:08:14,858 - Main.DeviceInt - INFO - Closed Device with handle num: 0
2016-12-13 17:08:14,858 - Main.DeviceInt - INFO - Forcing DLL handle closed

Process finished with exit code 1


thank you;

Andi

**Comment by fake-name** [comment]
Wow, well, that's a dumb oversight on my part. 

Can you try rolling back to the shipped DLL version? I suspect this issue is changes between the version 2 DLL (which the library was written for), and the version 3 DLL (which is the one they're currently shipping).

**Comment by andi2009** [comment]
hi,wolf:
I use your shipped version bb_api.dll file to test, it's seems the same logout as copy from spike; But i mind the file size of these two version is different, i think the interface function and arguments  list  may have no different.

Now, I can run normal about 'radio','status','traces','reset' leaf in all 9 test items;  
 
When i run r>python tests.py iq ,the logout as follow:
D:\python_bbapi\pySignalHound-master1\pySignalHound-master>python tests.py iq 
2016-12-14 08:58:25,825 - Main.DeviceInt - INFO - Opened Device with handle num: 0
2016-12-14 08:58:25,829 - Main.DeviceInt - INFO - Setting device frequency center & span settings.
2016-12-14 08:58:25,832 - Main.DeviceInt - INFO - Call to configureCenterSpan succeeded.
2016-12-14 08:58:25,835 - Main.DeviceInt - INFO - Setting device reference level and attentuation.
2016-12-14 08:58:25,839 - Main.DeviceInt - INFO - Call to configureLevel succeeded.
2016-12-14 08:58:25,842 - Main.DeviceInt - INFO - Setting device reference gain.
2016-12-14 08:58:25,845 - Main.DeviceInt - INFO - Call to configureGain succeeded.
2016-12-14 08:58:25,848 - Main.DeviceInt - INFO - Setting device IO Configuration.
2016-12-14 08:58:25,871 - Main.DeviceInt - INFO - Call to configureIO succeeded.
2016-12-14 08:58:25,877 - Main.DeviceInt - INFO - configureSweepCoupling Succeeded.
2016-12-14 08:58:25,885 - Main.DeviceInt - INFO - Call to initiate succeeded.
{'samples_per_sec': 20000000.0, 'bandwidth': 40000000, 'return_len': 524288}
1048576
Traceback (most recent call last):
  File "tests.py", line 562, in <module>
    go()
  File "tests.py", line 548, in go
    funcs[sys.argv[1]](sh)
  File "tests.py", line 105, in testIqStreaming
    data = sh.fetchRawSweep()
  File "D:\python_bbapi\pySignalHound-master1\pySignalHound-master\SignalHound\__init__.py", line 1587, in fetchRawSweep
    bufLen = 18688 * self.acq_conf["ppf"] * self.acq_conf["steps"]
KeyError: 'ppf'
2016-12-14 08:58:25,927 - Main.DeviceInt - INFO - Deleting SignalHound Interface Class
2016-12-14 08:58:25,928 - Main.DeviceInt - INFO - Force Closing.
2016-12-14 08:58:25,930 - Main.DeviceInt - INFO - Closing Device with handle num: 0
2016-12-14 08:58:25,957 - Main.DeviceInt - INFO - Running acquistion aborted.
2016-12-14 08:58:26,651 - Main.DeviceInt - INFO - Closed Device with handle num: 0
2016-12-14 08:58:26,654 - Main.DeviceInt - INFO - Forcing DLL handle closed

D:\python_bbapi\pySignalHound-master1\pySignalHound-master>

thank you.
Andi

**Comment by fake-name** [comment]
It appears that in this case, `configureRawSweep()` has not been called before `fetchRawSweep()`.

I suspect that issue is just the `iq` command line option not having been patched for changes in the SignalHound API. I initially wrote this API wrapper for a quite early version of their API (before the BB60C was even released), and they made a fair number of changes to how the lower-level functionality worked. I suspect I just never patched the raw sweep function testing utilities when I updated the API wrapper.

**Comment by andi2009** [comment]
hi,wolf:

thank you for your help.

I check the BB60C bb_api.dll firmware version :

Your package shipped version:
016-12-14 17:41:39,937 - Main.DeviceInt - INFO - Device firmware rev = 2.0.2
My new download version:
2016-12-14 17:37:06,322 - Main.DeviceInt - INFO - Device firmware rev = 3.0.4
So,the configureRawSweep() function is support in 2.0.2, but not in 3.0.4.
Maybe i would fix some file to compliance the 3.0.4.
Is there a suggestion for me? 

thank you!

Andi

**Comment by fake-name** [comment]
No, the test *doesn't call `configureRawSweep()`*. If you amend the test to use the API properly, it should work.
